sudo: required
env:
    global:
        - MAKEFLAGS="-j 8"
services:
    - docker

before_install:
    - docker build -t fernandodr19/react -f ./react/Dockerfile.dev ./react/

script:
    - docker run -e CI=true fernandodr19/react npm run test -- --coverage
