sudo: required
services:
    - docker

before_install:
    - docker build -t fernandodr19/react -f Dockerfile.dev ./react/

script:
    - docker run -e CI=true fernandodr19/react npm run test -- --coverage
